import { Document } from 'mongoose';
import { SchemaFactory, Schema, Prop, ModelDefinition } from '@nestjs/mongoose';

/**
 * Provides the name of the model required on {@linkcode AutoincrementModel}.
 */
export const AUTOINCREMENT_MODEL_NAME = 'AutoIncrement';

/**
 * Class used to store the sequences of the models in the documents to handle the autoincrement strategies
 */
@Schema({ timestamps: true })
export class AutoIncrement extends Document {
  /**
   * Model name
   */
  @Prop({ required: true, unique: true })
  modelN: string;

  /**
   * Sequence counter
   */
  @Prop({ default: 0 })
  seq: number;

  /**
   * Date when the object was last modified.
   */
  updatedAt: Date;

  /**
   * Date when the object is created.
   */
  createdAt: Date;
}

/**
 * Saves the mongoose schema generated by {@linkcode SchemaFactory}.
 */
export const AutoIncrementSchema = SchemaFactory.createForClass(AutoIncrement);

/**
 * Used to provide {@linkcode AutoIncrementSchema} with {@linkcode AUTOINCREMENT_MODEL_NAME} as a model to mongoose.
 */
export const AutoIncrementModel: ModelDefinition = {
  name: AUTOINCREMENT_MODEL_NAME,
  schema: AutoIncrementSchema,
};

export default AutoIncrementModel;
